spring.application.name=rewards-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rewards_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:213.199.42.57}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:students}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:Ut3c2026}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VHOST:/}